backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow # Enables drafts
media_folder: static/uploads # Media files will be stored in the repo under static/images/
public_folder: /uploads # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the GUI
    folder: "static/_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", dateFormat: "DD MMM YYYY" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }

  - name: "authors" # Used in routes, e.g., /admin/collections/blog
    label: "Authors" # Used in the GUI
    folder: "static/_authors" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "author" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Photo", name: "photo", widget: "image", required: false}
      - { label: "Bio", name: "bio", widget: "text", required: false}
      - { label: "Body", name: "body", widget: "markdown", required: false }
